# Generated by Django 5.1.7 on 2025-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(upload_to='events/images'),
        ),
    ]
