# Generated by Django 5.1.7 on 2025-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='projects/images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf',
            field=models.FileField(upload_to='projects/pdfs'),
        ),
    ]
