# Generated by Django 5.1.7 on 2025-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profile_pic',
            field=models.ImageField(upload_to='team/images'),
        ),
    ]
